unstable_features = true
color = "Always"

blank_lines_upper_bound = 2

max_width = 90
use_small_heuristics = "Max"

imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"

comment_width = 90
doc_comment_code_block_width = 90
wrap_comments = true
format_code_in_doc_comments = true
normalize_doc_attributes = true

combine_control_expr = false

struct_field_align_threshold = 20
enum_discrim_align_threshold = 20

hex_literal_case = "Upper"

match_arm_leading_pipes = "Always"
match_block_trailing_comma = true

use_field_init_shorthand = true

merge_derives = false

trailing_comma = "Always"

use_try_shorthand = true