[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[toolchain]
channel = "stable"

[dependencies]
rand = "0.10.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
